FROM python:3.9-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar el archivo de dependencias
COPY requirements.txt requirements.txt

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los archivos de Streamlit
COPY . .

# Exponer el puerto de Streamlit
EXPOSE 8501

# Comando para iniciar la app de Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

# docker-compose down --volumes --remove-orphans    # para eliminar
# http://localhost:8501
