version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - MLFLOW_TRACKING_URI=https://dagshub.com/colome8/PROYECTO_OSKU.mlflow
    volumes:
      - ./api/models:/app/models  # Asegura que los modelos están disponibles dentro del contenedor

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    depends_on:
      - api

# docker-compose down --volumes --remove-orphans    # para eliminar
# http://localhost:8501      